### ISSUE TITLE
Upload an Image

### ISSUE THREAD

**Issue by csarigumba** [dartsidedev/twitter_intent#1]
As the title says, is it possible to upload an image using the library?

**Comment by vincevargadev** [comment]
Currently, the library doesn't support uploading images to Twitter.

The library is based on [Twitter's web intents](https://developer.twitter.com/en/docs/twitter-for-websites/web-intents/overview) and as far as I know, they do not support uploading/sharing of images.

If you think I made a mistake interpreting what's possible with Twitter web intents, let me know, and I'll reopen the issue and add it to the library.

I'd close this issue as (AFAIK) there is no way that this library can add support for uploading images, as that is not supported by Twitter's web intents.

The closest thing you can do is creating a [retweet intent](https://pub.dev/packages/twitter_intent#retweet) for a tweet that has an image, for example: https://twitter.com/intent/retweet?tweet_id=1571194776384413697 `RetweetIntent(tweetId: '1571194776384413697')`. I assume this is probably not what you wanted, but in case it helps.
